apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-cloud-secu
  #namespace: cubeone-test
  labels:
    app: db-cloud-secu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-cloud-secu
  template:
    metadata:
      labels:
        app: db-cloud-secu
    spec:
      containers:
      - name: db-cloud-secu
        image: 172.30.1.90:5000/db_cloud_13_3_secur:2.1
        ports:
        - containerPort: 5432
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/db_data/data/"
          name: data-volume
          #        - mountPath: "/db_conf/"
          #name: conf-volume
        command: ['/bin/sh']
        args: ['-c', '/home/db/DB_start.sh']
        env:
        - name: REPOPORT
          value: "5432"
        - name: AGENTIP
          value: db-cloud-secu.default
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: db-data-pvc
          #claimName: db-secu-data-pvc
          #      - name: conf-volume
          #persistentVolumeClaim:
          # claimName: db-conf-pvc
          #claimName: db-secu-arc-pvc
#      - name: log-volume
#        persistentVolumeClaim:
#          claimName: db-secu-log-pvc
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
