apiVersion: v1
kind: Service
metadata:
  name: nginx 
  labels:
    app: nginx
spec:
  ports:
  - port: 80 
    targetPort: 80 
    name: nginx-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
