apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: ws-pv
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
