apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-pv
  labels:
    location: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Users/jacejeong/k8s/pv01
  accessModes: 
    - ReadWriteMany
